
def commonWords():
    listOfCommonWords = ['i',
      'a',
      'of',
      'me',
      'my',
      'im',
      'is',
      'it',
      'on',
      'so',
      'to',
      'up',
      'all',
      'and',
      'for',
      'get',
      'how',
      'new',
      'out',
      'the',
      'use',
      'for',
      'best',
      'have',
      'name',
      'next',
      'take',
      'that',
      'what',
      'image',
      'something',
    ]
    return listOfCommonWords

def emailPhrases():
    listOfEmailPhrases = ['Skip to content',
      'Using',
      'with screen readers',
      'Search',
      'Mail',
      'COMPOSE',
      'Labels',
      'Inbox',
      'Starred',
      'Sent Mail',
      'Drafts',
      'More',
      '---------- Forwarded message ----------',
      'From: ',
      'Date: ',
      'Subject: ',
      'To: ',
      'Click here to Reply or Forward',
      'GB',
      'GB used',
      'Manage',
      'Program Policies',
      'Powered by Google',
      'Last account activity:',
      'hour ago',
      'hours ago',
      'Details',
    ]
    return listOfEmailPhrases
